ALTER TABLE IF EXISTS group_messages ADD COLUMN IF NOT EXISTS read_at TIMESTAMP NULL;
ALTER TABLE IF EXISTS event_messages ADD COLUMN IF NOT EXISTS read_at TIMESTAMP NULL;
ALTER TABLE IF EXISTS group_messages ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP NULL;
ALTER TABLE IF EXISTS event_messages ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP NULL;
ALTER TABLE IF EXISTS group_messages ADD COLUMN IF NOT EXISTS reaction_users VARCHAR(4000) NULL;
ALTER TABLE IF EXISTS event_messages ADD COLUMN IF NOT EXISTS reaction_users VARCHAR(4000) NULL;
