ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS profile_image;
ALTER TABLE IF EXISTS group_invitations ADD COLUMN IF NOT EXISTS is_read BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS event_invitations ADD COLUMN IF NOT EXISTS is_read BOOLEAN NOT NULL DEFAULT FALSE;
